---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-a
  labels:
    app: app-a
spec:
  replicas: 5
  selector:
    matchLabels:
      app: app-a
  template:
    metadata:
      labels:
        app: app-a
    spec:
      containers:
      - name: nginx
        image: docker.io/monachus/rancher-demo # Portnumber 8080
        resources:
          limits:
            memory: 512Mi
            cpu: "0.5"
          requests:
            memory: 256Mi
            cpu: "0.2"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: app-a
spec:
  # type: LoadBalancer
  type: NodePort
  selector:
    app: app-a
  ports:
  
    - protocol: TCP
      port: 9999
      targetPort: 8080
      nodePort: 30304
