apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: kyc-pioncode
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kyc-pioncode
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 10

---
apiVersion: v1
kind: Service
metadata:
  name: kyc-pioncode-nodeport
spec:
  type: NodePort
  selector:
    app: kyc-pioncode
  ports: 
    - name: pincode
      port: 30005
      targetPort: pincode
      nodePort: 30005      


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kyc-pioncode
  labels:
    app: kyc-pioncode
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kyc-pioncode
  template:
    metadata:
      labels:
        app: kyc-pioncode
    spec:
      containers:
      - name: kyc-pioncode
        image: docker.io/nginx:latest
        imagePullPolicy: Never
        resources:
          limits:
            memory: 512Mi
            cpu: "0.25"
          requests:
            memory: 512Mi
            cpu: "0.25"
        ports:
        - containerPort: 30005
          name: pincode
